[project]
name = "data-quality-measurement"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=3.0.1",
    "ruff>=0.15.2",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
]
